//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/AvatarProperty.proto
namespace proto.AvatarProperty
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AvatarProperty")]
  public partial class AvatarProperty : global::ProtoBuf.IExtensible
  {
    public AvatarProperty() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private float _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private float _posZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private float _rotX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotX
    {
      get { return _rotX; }
      set { _rotX = value; }
    }
    private float _rotY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rotY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotY
    {
      get { return _rotY; }
      set { _rotY = value; }
    }
    private float _rotZ;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rotZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotZ
    {
      get { return _rotZ; }
      set { _rotZ = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}