//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/ProtoPong.proto
namespace proto.ProtoPong
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoPong")]
  public partial class ProtoPong : global::ProtoBuf.IExtensible
  {
    public ProtoPong() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}